name: Nake cookies and build images

env:
  DOCKER_BUILDX: "0.3.1"

on: ["push", "pull_request"]

jobs:
  cookie-cutter-osparc:
    name: testing cookie-cutter-osparc
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [3.10]
        os: [ubuntu-20.04]
        docker_buildx: [v0.8.2]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: setup docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: ${{ matrix.docker_buildx }}
          driver: docker-container
      - name: setup python environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
          cache-dependency-path: "**/requirements*.txt"
      - name: set dev environs
        run: make devenv
      - name: test cookiecutter
        run: |
          source .venv/bin/activate
          make tests